name: Multi Repo Code Analysis

on:
  workflow_dispatch:
    inputs:

      organization:
        description: "GitHub Organization"
        required: true
        default: "ios-mcn-core"

      repositories:
        description: "Comma separated repo names or 'all'"
        required: true
        default: "all"

      # ADD THIS NEW INPUT
      target_commit:
        description: "Old version to compare from (e.g. v0.3.0.iosmcn.core)"
        required: true
        default: "v0.3.0.iosmcn.core"

      output_format:
        description: "csv/xlsx/both"
        required: true
        default: "xlsx"
        

jobs:

  analysis:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Automation Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas openpyxl xlsxwriter requests

      - name: Run Analysis
        env:
          ORG_PAT: ${{ secrets.ORG_PAT }}
          ORG: ${{ github.event.inputs.organization }}
          REPOS: ${{ github.event.inputs.repositories }}
          TARGET_COMMIT: ${{ github.event.inputs.target_commit }}  ## Added this line
        run: |
          python scripts/run_analysis.py

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: analysis-reports
          path: reports/
